### ISSUE TITLE
hiding play/pause animated center button when stopping and starting video

### ISSUE THREAD

**Issue by Nicknaem** [nralbrecht/youtube-hide-controls#11]
when im trying to clip some part of the video, having hidden controls is great, thank you so much for doing this plugin, but it would be great to be able to hide play/pause animated center button when stopping and starting video

**Comment by nralbrecht** [comment]
I like the idea, the video recommendations at the end of the video fall in to a similar category i guess. 

Currently i am doing a major rework of the add-on code. I will put this on the list.

**Comment by nralbrecht** [comment]
I released a new update (v3.0.0) that implements options to hide some video overlays as well as the center play/pause animation.

**Comment by Nicknaem** [comment]
thanks a lot <3
