### ISSUE TITLE
Weird behaviour/bug after recent update.

### ISSUE THREAD

**Issue by shukrifathil** [nralbrecht/youtube-hide-controls#14]
I don't know how to say it but sometimes the extension works and sometimes it doesn't. The Invert Trigger needs to be disabled and re-enabled for it to work like it usually does.

**Comment by dkaknbk** [comment]
I have had the issue in the last couple of days, the extension keeps working, but in the middle of a session the inversion is disabled at random and the only way to make it function as intended again is to uncheck and recheck the box in the options, reseting the browser doesn't fix it.

**Comment by KrazyLurt** [comment]
Same, rolled back from v3.0.
Inverted didnt work properly, fullscreen only didnt work etc.
No big deal as 2.6.1 is great.

**Comment by nralbrecht** [comment]
I am sorry for the trouble. Unfortunately I was not yet successful at reproducing the problem.
Could you share the Firefox version and the add-on config values you are using.

**Comment by dkaknbk** [comment]
Thanks for taking a look! I am using Firefox 105.0.1 (64-bit) and this is my configuration of the add-on:

![firefox_2022-09-26@07_45_01](https://user-images.githubusercontent.com/78300742/192202067-bb7318bf-c287-484c-a441-dd0dcdc9d682.jpg)

**Comment by nralbrecht** [comment]
I think I found and fixed the problem. The internal state was not initialized correctly due to a race condition. I will package and release v3.0.1 as soon as possible.
