### ISSUE TITLE
Functionality disabled by default on Firefox

### ISSUE THREAD

**Issue by Makumasa** [nralbrecht/youtube-hide-controls#15]
Not sure how long it's been this way, but installing this addon for Firefox has both mouse interaction and hotkey disabled by default, meaning the addon doesn't actually do anything unless you go into the settings and manually flip one of these on. It's quite unintiutive, since myself (and, I imagine, many others) expect the default behavior to be at least mouse interaction to hide fullscreen controls.

**Comment by nralbrecht** [comment]
Oh! Thanks for letting me know :facepalm:

**Comment by nralbrecht** [comment]
Settings have bin changed to the `Hide when mouse is at border` preset in [v3.0.2](https://github.com/nralbrecht/youtube-hide-controls/releases/tag/v3.0.2).
