### ISSUE TITLE
Add-on doesn't do anything

### ISSUE THREAD

**Issue by cjskama** [nralbrecht/youtube-hide-controls#18]
Installed the add-on to Firefox. Then when I pause a YouTube video, the commands at the bottom of the screen do not go away no matter where I move the cursor.

**Comment by nralbrecht** [comment]
Sorry for the late response. Could you share your add-on settings. It heavily depends on the settings whether something is supposed to happen. 

I would also be interested in what you expected to happen. That could help in re reconsidering the wording of the add-on description and settings or even a new feature.

**Comment by cjskama** [comment]
Thanks for the response.

As to what I expect (and tell me if I'm wrong). If you are on Youtube, and
you press pause (||), a long white line appears at the bottom of the
display, and below that several icons. I expect this app to remove all of
that clutter so that all I see is the actual image.

here are the settings, I think.
[image: image.png]

**Comment by nralbrecht** [comment]
Your Image is unfortunately not able to be displayed.

With the default settings, the controls you described will be hidden when you move the mouse cursor to the left and right five pixels of the Firefox window.

You can change the behavior using the settings. You might want to try the "Show when mouse is over controls" preset. By default that preset only works in fullscreen. You can also configure a hotkey to toggle the controls.

If you have any questions and recommendations on how to communicate this better, please let me know.
