### ISSUE TITLE
Permanently hide controls

### ISSUE THREAD

**Issue by Trancol** [nralbrecht/youtube-hide-controls#2]
Please add a way to permanently hide controls and only bring them up if the mouse cursor is hovered near the bottom side.

**Comment by nralbrecht** [comment]
Here you go. You will find "invert trigger" in the addon options. Activate it and change the trigger distance from the bottom to somewhere around 70. Than this addon should behave the way you wanted.

Please let me know of any further problems you encounter.
Cheers!

**Comment by Trancol** [comment]
Thanks. It works perfect.

**Comment by nralbrecht** [comment]
I noticed that to. But I could not figure out why. Do you know a way to reproduce this reliable?

**Comment by nralbrecht** [comment]
Cool! Thank you.

**Comment by nralbrecht** [comment]
Should be fixed now.
