### ISSUE TITLE
Can't seem to save settings in the updated version

### ISSUE THREAD

**Issue by whyie** [nralbrecht/youtube-hide-controls#21]
In the old version, it works fine for me. Then today I noticed my hotkey for hiding controls didn't work. I checked the options and it has a new UI, so I guess you updated it. In this new UI I can't save my settings for hotkey. There's no save button either in the option menu.

**Comment by whyie** [comment]
Works fine after reinstalling the extension

**Comment by nralbrecht** [comment]
Perfect 🙂
