### ISSUE TITLE
Hide when paused

### ISSUE THREAD

**Issue by ahmedtds** [nralbrecht/youtube-hide-controls#5]
Hi, only reason I needed an extension like this to use it to hide control when video is paused but this extension doesn't seem to be able to do that. Can you make it happen? Thanks.

**Comment by nralbrecht** [comment]
Was the video in full screen when you tried to hide the controls? Currently the add-on is made to only work in full screen, if this is the problem is this some thing you would want to see?

**Comment by ahmedtds** [comment]
Ok sorry, I was not aware this extension only works on full-screen. Tried on full-screen now and it works as expected with paused video. But it would be nice if you made the extension work on non-fullscreen too. Maybe make it optional.

**Comment by nralbrecht** [comment]
No worries. I though of this a while back too but never hat a reason to implement it.
I will work on this in the coming days.

**Comment by nralbrecht** [comment]
I added a option to also hide controls outside of the full screen. The addon is currently being reviewed and will be available shortly. Let me know if this works for you.

**Comment by ahmedtds** [comment]
Thanks a lot for taking your time, I'm trying but I noticed it doesn't save the setting for the "Only fullscreen" option, reverts to be enabled after browser restart or something.
Also it doesn't work when video is paused I think

**Comment by nralbrecht** [comment]
Oh i missed that while testing :smiley: The state of the check box was always checked when visiting the option page.
I pushed a new update that is already reviewed and live.
