### ISSUE TITLE
Request: A way to disable controls even if mouse moves using a hotkey and/or preference checkbox

### ISSUE THREAD

**Issue by IITFA** [nralbrecht/youtube-hide-controls#8]
So, I tried this addon because I get very annoyed when my mouse moves a fraction of a mm and suddenly all the video controls are all over the screen when in fullscreen. It seems this addon doesn't have a way to disable the controls even if the mouse moves, so I am suggesting this feature.

Maybe a hotkey can be used to disable the controls in fullscreen even if the mouse moves and/or a preference checkbox to do so.

Thank you.

**Comment by nralbrecht** [comment]
Closing do to it being implemented by #10
